### ISSUE TITLE
Fix console commands.

### ISSUE THREAD

**Issue by CosmicStar98** [Seamusmario/BonziWORLD-patched#3]
![image](https://user-images.githubusercontent.com/58494315/171747866-72a0e398-5edd-43ae-a408-ebd3a1b9c08b.png)

**Comment by Seamusmario** [comment]
The kick command is not available in 1.4.2

**Comment by CosmicStar98** [comment]
no. im talking about 1.6.0

**Comment by CosmicStar98** [comment]
can you fix the commands for 1.6.0 please. none of them work correctly

**Comment by CosmicStar98** [comment]
i did that. the issue is line 71 of console.js in versions past 1.4.2
"cannot read properties of undefined '.function' "

**Comment by Seamusmario** [comment]
![image](https://user-images.githubusercontent.com/33694155/171758475-0647299b-b1e9-4754-855e-38434220b46d.png)

**Comment by Seamusmario** [comment]
> ![image](https://user-images.githubusercontent.com/33694155/171758475-0647299b-b1e9-4754-855e-38434220b46d.png)

This right here is the actual usage of the command. You put the name of the command first, and then put the arguments.
Otherwise, it will simply result in a error.

**Comment by duckduckstab1** [comment]
Close issue?
